name: Codacy Scan

on:
  push:
    branches:
      - main
      - PreProd

jobs:
  codacy-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Codacy CLI
        run: curl -sL https://download.codacy.com/cli/latest/linux/x86_64/codacy | sudo tee /usr/local/bin/codacy
      
      - name: Codacy Scan
        run: codacy analyze --format text -o results.txt

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: codacy-results
          path: results.txt
    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}