name: Codacy Security Scan

on:
  push:
    branches: [ "master", "main" , "PreProd" ]
jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          output: results.json  # Cambiado a .txt para archivo de texto
          format: json  # Cambiado a texto
          # Adjust severity of non-security issues
          gh-code-scanning-compat: true
          # Force 0 exit code to allow text file generation
          # This will hand over control about PR rejection to the GitHub side
          max-allowed-issues: 2147483647
      
      # Upload the text file generated in the previous step
      - name: Upload text results file
        uses: actions/upload-artifact@v3
        with:
          name: codacy-security-results
          path: results.json  # Archivo